// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARy0LVd9jJnjoBlV7C3qKFerAR4bJ72_Y',
    appId: '1:746243407219:web:066002182fb5a2f7875906',
    messagingSenderId: '746243407219',
    projectId: 'rugswebsitedemo',
    authDomain: 'rugswebsitedemo.firebaseapp.com',
    storageBucket: 'rugswebsitedemo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeerfSwdRLM8ZKksSkGSzDsv55ozV44sk',
    appId: '1:746243407219:android:03dcae81276f7564875906',
    messagingSenderId: '746243407219',
    projectId: 'rugswebsitedemo',
    storageBucket: 'rugswebsitedemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWDEjn90XY_hGCavXAr3hfI7lyCGDgSws',
    appId: '1:746243407219:ios:1be4d39abadb5270875906',
    messagingSenderId: '746243407219',
    projectId: 'rugswebsitedemo',
    storageBucket: 'rugswebsitedemo.appspot.com',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWDEjn90XY_hGCavXAr3hfI7lyCGDgSws',
    appId: '1:746243407219:ios:1be4d39abadb5270875906',
    messagingSenderId: '746243407219',
    projectId: 'rugswebsitedemo',
    storageBucket: 'rugswebsitedemo.appspot.com',
    iosBundleId: 'com.example.website',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARy0LVd9jJnjoBlV7C3qKFerAR4bJ72_Y',
    appId: '1:746243407219:web:b4eb37ca2ea1f04e875906',
    messagingSenderId: '746243407219',
    projectId: 'rugswebsitedemo',
    authDomain: 'rugswebsitedemo.firebaseapp.com',
    storageBucket: 'rugswebsitedemo.appspot.com',
  );
}
